#!/bin/bash
shopt -s dotglob
cd ~/configs
for file in *; do
    if [ "$file" != ".git" -a "$file" != "deploy" -a "$file" != "deploy_encrypted" -a "$file" != "encrypted" ]; then 
        ln -s configs/"$file" ~
    fi
done
